### ISSUE TITLE
Release for 1.0

### ISSUE THREAD

**Issue by Nosferican** [samoconnor/LazyJSON.jl#1]
Issue to track a release for Julia 1.0.

**Comment by samoconnor** [comment]
Some iteration protocol changes are done: https://github.com/samoconnor/LazyJSON.jl/commit/f6be3fc1c1da54823ecdb83858d0e72e197454bf

I'm working on some changes to get IOString working again. It seems that the Base.AbstractString interface has changed a bit (probably as a side effect of the iteration protocol change).

**Comment by Nosferican** [comment]
Perfect. I am just waiting on a 1.0 release to update my package. Thanks for the update!

**Comment by samoconnor** [comment]
Are you using `IOString` at all? (i.e. passing an IO to `LazyJSON.value` or `LazyJSON.parse`?)
If not, I could just disable that for now and do a release where the core `LazyJSON.value(::Union{Base.String, Base.SubString})` works.

**Comment by Nosferican** [comment]
I don't think so. I run it on `AbstractString`,
```
using LazyJSON: value
using LazyJSON.PropertyDicts: get
...
response = request("GET", url, header)
jsontext = String(getfield(response, :body))
jsontext == "{}" && return DataFrame(Ts, Ns, 0)
json = value(jsontext)
```

**Comment by samoconnor** [comment]
So, current master is now passing the tests on 1.0 (with IOStrings and SplicedStrings disabled)

**Comment by Nosferican** [comment]
Thanks!

**Comment by samoconnor** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16796#issuecomment-412704896

**Comment by samoconnor** [comment]
https://github.com/samoconnor/LazyJSON.jl/releases/tag/v0.0.5
