### ISSUE TITLE
x is not defined

### ISSUE THREAD

**Issue by programmeroftheeve** [samoconnor/LazyJSON.jl#2]
I came across an issue using a JSON array as a top level element with an IOStream.

https://github.com/samoconnor/LazyJSON.jl/blob/2a66639fca3ea8f3428c93e0f59398cb4f4aa6f6/src/AbstractArray.jl#L37

```julia
io = IOBuffer("""[
              {"type":"Bar","event":{"a":"Hello","foo":{"a":1,"b":2}}},
              {"type":"Bar","event":{"a":"Hello","foo":{"a":1,"b":2}}}
              ]""")
o = LazyJSON.value(io) # This breaks on doing the repl print
o[1] # This just breaks
```

**Comment by samoconnor** [comment]
Thanks for reporting that!

**Comment by samoconnor** [comment]
https://github.com/samoconnor/LazyJSON.jl/releases/tag/v0.0.6
https://github.com/JuliaLang/METADATA.jl/pull/18459
