### ISSUE TITLE
Moving `PropertyDicts.jl` to its own package?

### ISSUE THREAD

**Issue by DilumAluthge** [samoconnor/LazyJSON.jl#22]
I'd like to use the functionality in this file (https://github.com/JuliaCloud/LazyJSON.jl/blob/master/src/PropertyDicts.jl) without loading the full package.

What do you think about moving the PropertyDicts functionality to a tiny standalone package?

**Comment by mattBrzezinski** [comment]
I think we can do this quite easily. The `PropertyDicts` are not being exported, so we should be able to pull this out quite easily. I'm just unsure which ecosystem this should live in, `JuliaCloud` doesn't seem to fit `PropertyDicts`. Any suggestions?

**Comment by DilumAluthge** [comment]
Hmmm. Maybe JuliaCollections?

**Comment by mattBrzezinski** [comment]
Seems like an appropriate place, I don't have permissions in that organization. If you do, could you create the repository? I can spend some time this weekend pulling it out and making the PR. If not, it looks like @oxinabox can!

**Comment by DilumAluthge** [comment]
I don't have the permissions unfortunately.

**Comment by oxinabox** [comment]
I have invited you both as members of the org, and i have granted members of the org repo-creation permissions.

Being members also gives you merge rights on everything else, feel encouraged to use them.
Follow ColPrac for all JuliaCollections repos.

https://github.com/SciML/ColPrac

**Comment by DilumAluthge** [comment]
https://github.com/JuliaCollections/PropertyDicts.jl

**Comment by mattBrzezinski** [comment]
Should updated this to remove all usages of `PropertyDicts` and add the package itself to this project.

**Comment by DilumAluthge** [comment]
Good idea. Will need to wait until the package is registered though: https://github.com/JuliaRegistries/General/pull/21641
