### ISSUE TITLE
no method matching `AbstractFloat(::LazyJSON.Number{String})`

### ISSUE THREAD

**Issue by catethos** [samoconnor/LazyJSON.jl#4]
Given that I have the following json and struct, I cannot convert the json object to the struct
```
json = """
{
    "a":1.0,
}
"""

struct W
    a :: AbstractFloat
end

```

```
val = LazyJSON.parse(json)
convert(W, val)
```
give me
```
MethodError: no method matching AbstractFloat(::LazyJSON.Number{String})
```

However, if I change the `AbstractFloat` to `Float64` or `Number` then it works.  Do we need to implement `AbstractFloat(::LazyJSON.Number{String})` or this is intended?

**Comment by EricForgy** [comment]
`AbstractFloat` is abstract :)

Maybe you can try a parametric struct?

```julia
struct W{F<:AbstractFloat}
    a::F
end
```

?

**Comment by catethos** [comment]
`Number` is abstract too, but it works

**Comment by samoconnor** [comment]
Thanks for the report @catethos.
I'd be happy to accept a PR that adds `Base.AbstractFloat(n::JSON.Number)::AbstractFloat = Base.Number(n)` here:
https://github.com/samoconnor/LazyJSON.jl/blob/master/src/Number.jl#L148

Or, I'll add it myself when I next come back to doing maintenance on this package (after a long list of other priorities).

**Comment by catethos** [comment]
Done. I am closing the issue now
