### ISSUE TITLE
Julia 1.2: `UndefVarError: next_continued not defined`

### ISSUE THREAD

**Issue by omus** [samoconnor/LazyJSON.jl#5]
As of JuliaLang/julia#30965 the `Base.next_continued` function was renamed to `Base.iterate_continued`.

**Comment by samoconnor** [comment]
Could you try removing `Base.` from this line (i.e. change `next_continued` into a private local function) ?

https://github.com/samoconnor/LazyJSON.jl/blob/2a66639fca3ea8f3428c93e0f59398cb4f4aa6f6/src/AbstractString.jl#L306

**Comment by omus** [comment]
Changing the function to be local to the module works. Do you want me to make a PR with that change?
