### ISSUE TITLE
Make v0.1.1 release

### ISSUE THREAD

**Issue by omus** [samoconnor/LazyJSON.jl#8]
Including https://github.com/samoconnor/LazyJSON.jl/pull/7 which fixes the package on nightly

**Comment by omus** [comment]
@samoconnor?

**Comment by samoconnor** [comment]
Done.
I've also moved LazyJSON.jl to JuliaCloud so that others can do fixes/tags at times that I am not available.

**Comment by omus** [comment]
Very much appreciated. Thanks @samoconnor!
